ifndef::imagesdir[:imagesdir: ../images]
:data-uri:

=== 解析器基础

==== 设计目的

Zero UI中的一个很大的亮点就是 **属性解析器**，属性解析器也可以称为配置解析器，您可以通过十分简洁的默认代码将属性解析成 `Json Object` 的方式来标准化配置格式。属性解析器的设计目的如下：

1. 让开发人员更集中于配置中和业务直接相关的部分而 **忽略配置的数据格式**。
2. 对 Json 格式的配置进行压缩，有了属性表达式之后原始配置信息会压缩到 **20%** 的体积，大大减少了开发人员对配置的实施量。
3. 属性标准化：针对部分特殊属性可执行标准化操作，包括效果、文本、标签、图标等。

Zero UI中的属性解析器主要应用于如下场景（默认启用）：

- 常用的表单字段，配合 `AntD` 实现模型属性的配置化定制。
- 常用的列表列渲染，支持各种不同的列渲染结果。
- 窗口、请求等常用属性解析器，可提高开发人员开发这些定制组件的效率。

==== 解析格式

前端配置的通用解析格式主要有如下三种：

1. （最简）纯字符串解析格式，如：

+
--
[source,json]
----
    "title,标题,,,,placeholder=格式如：***公司,normalize=text:128"
----
--

2. （高频）开发专用格式，如：

+
--
[source,json]
----
{
    "metadata": "companyId,所属公司,,,aiTreeSelect,placeholder=（请选择所属公司）",
    "optionJsx.config.datum": "source=resource.companys,value=key,label=name",
    "optionJsx.config.tree": "text=name,parent=companyId",
    "optionJsx.config.selection": "mode=FULL",
    "optionConfig.rules": [
        "required,请选择员工所属的公司！"
    ]
}
----

开发专用格式和其他两种格式的区别在于：

- 这种格式通常会有专用的 `metadata` 属性作可解析部分，**可解析部分** 的格式和最简格式中的字符串格式是一致的。
- 这种格式支持属性的拉平语法，如示例中的 `optionJsx.config.datum` 这种键值，Zero UI会将它自动解析。
- 这种格式除开 `metadata` 之外，会带上部分附加配置（半Json结构），这些结构一般是为 **复杂场景** 而量身打造的，所以其作用主要是补充。

--

3. （完整）标准格式，如前文中格式展开之后如下：

+
--
[source,json]
----
{
    "field": "companyId",
    "optionItem": {
        "label": "所属公司"
    },
    "$render": "aiTreeSelect",
    "optionJsx":{
        "placeholder": "（请选择所属公司）",
        "config":{
            "datum": {
                "source": "resource.companys",
                "value": "key",
                "label": "name"
            },
            "tree": {
                "text": "name",
                "parent": "companyId"
            },
            "selection":{
                "mode": "FULL"
            }
        }
    },
    "optionConfig": {
        "rules": [
            {
                "type": "required",
                "message": "请选择员工所属的公司！"
            }
        ]
    }
}
----

标准格式在整个配置表中是最规范的，如果使用程序生成对应的格式，推荐使用标准格式；标准格式会跳过属性解析部分，直接将格式中的JSON作为配置来执行处理，这种格式的缺陷是长度比较大（完整格式是最长的），开发人员在书写时略有不方便。
--

[CAUTION]
====
参考表格看看三种不同格式的使用场景，让开发人员更清楚其用法：

[options="header",cols="2,2,6"]
|====
|格式|场景|说明
|最简格式|简易配置|如果您想要书写的配置可直接使用最简格式配置，那么采用最简格式属于最优解。
|开发格式|复杂配置|若某些配置中依赖比较复杂的规则，如：**复杂组件、验证规则、渲染分流、自定义组件、远程参数、流程配置** 等这种复杂场景中往往需要采用此种格式。
|标准格式|机器配置|若您使用的是 **开发中心** 的工具对配置进行生成或标准化，那么采用这种格式是最优，跳过属性解析部分且不需使用人工书写。
|====

==== 

==== 拉平语法

拉平语法是 Zero UI 中书写配置的另外一大亮点，其目的也是为了 **压缩配置体积**，参考如下配置：

[source,json]
----
{
    "optionJsx":{
        "style":{
            "height":300
        },
        "config":{
            "title":[
                "left",
                "right"
            ]
        }
    }
}
----

上述配置若是手工书写会写一堆 `{}` 或 `[]` 来展开完整配置，阅读比较规范，但体积（行数）偏高，有用的信息只有 1/3 左右，使用了拉平配置后其内容如下：

[source,json]
----
{
    "optionJsx.style.height": 300,
    "optionJsx.config.title": [
        "left",
        "right"
    ]
}
----

拉平配置中默认格式可采用不同方式拉平，如上述配置也可以写成（只要符合拉平原理的格式都是这种格式支持的，这点大大提高了开发人员书写配置的自由度）：

[source,json]
----
{
    "optionJsx":{
        "style.height": 300,
        "config.title": [
            "left",
            "right"
        ]
    }
}
----

==== 表达式

一般属性表达式的格式如：`v0,v1,v2,v3`，这种格式下，对应的 `v0` 表示索引为 `0` 的值，这种场景下会根据不同的 **组件**，其属性名有所区别，若某个一索引中无值，则需置空，若从某一个属性开始全部为空则可不用考虑，如：

[source,bash]
----
# 如下边表达式 v2, v3 无值，但由于 v4=aiTextArea，所以需占位符
name,姓名,,,aiTextArea

# 下边格式 v2 开始全部为空
title,标题
----

若在使用过程中遇到了扩展属性，则要启用 `$KV$` 占位符，`$KV$` 占位符用于填充 **原子解析器** 中的原子属性，通常使用 `key=value` 的格式来执行解析，此处的 `key=value` 在后续的 **原子解析器** 章节中会有所说明。