ifndef::imagesdir[:imagesdir: ../images]
:data-uri:
:table-caption!:

=== 验证规则

验证规则主要针对 `optionConfig.rules` 的配置部分的配置生效，您可以直接配置各种有用的验证器。参考配置：

[source,json]
----
{
    "optionConfig.rules": [
        "required,请输入仓库名称，名称不可为空！"
    ]
}
----

上述配置是最常用的配置，此处的规则中也可以直接使用 `AntD` 的默认验证器配置，由于默认验证器配置在官方文档中存在，所以就不在这里重复，本章主要讲解部分常用的 **自定义验证器**。

====
下边验证器都是自定义扩展验证器，所以标题中的值等价于 `validator=<title>`。
====

==== existing

存在性验证专用配置（高频验证器）。参考配置：

[source,json]
----
{
    "validator": "existing",
    "message": "对不起，支行名称重复！",
    "config": {
        "uri": "/api/bank/existing",
        "method": "POST",
        "params": {
            "sigma": "PROP:app.sigma"
        }
    }
}
----

[CAUTION]
====
假设有表结构

[options="header"]
|====
|属性|数据库列
|`key` | `KEY`
|`code` | `CODE`
|`docId` | `DOC_ID`
|====

此处配置可追加一个特殊配置 `alias` 用于对字段属性进行 **映射** 配置，在存在性检查的编辑界面中，检查时要移除掉当前记录的存在，简单说若您系统中存在一个 `A` 的属性为 `code（CODE）` 的记录，那么此处应该在SQL中您应该追加：

[source,sql]
----
KEY <> '<key>'
----

上述表达式中 `<key>` 中为 **主键排除** 模式，这种存在性检查只在编辑模式中生效以防止编辑和添加的存在性检查逻辑，简单说：

- 添加记录时，若系统中存在 `A` 的记录，则无法添加。
- 编辑记录中，若系统中存在 `A` 的记录且主键和当前数据记录主键一致，则表示同一条记录，依旧允许更新。

`alias` 则用于配置条件中的左边属性，示例：

[source,json]
----
{
    "validator": "existing",
    "message": "对不起，法规编号重复！",
    "config": {
        "uri": "/api/doc/existing",
        "method": "POST",
        "params": {
            "sigma": "PROP:app.sigma"
        },
        "alias": {
            "key": "docId"
        }
    }
}
----

上述属性 `alias.key` 是主键固定值，之所以是对象模式是为了考虑后期复合主键（多个字段做主键）的情况，上述结构会生成下边SQL语句：

[source,sql]
----
DOC_ID <> '<key>'
----

来执行编辑过程中存在性检查的当前记录排除，默认情况若主键本身是 `key` 属性，则可以不用配置（大量场景可不用配置）。
====

==== uri

远程延迟验证，更广义的 Ajax 验证，可实现各种 **不可思议** 的验证方式，开发人员阅读源代码自行理解。

==== filename

合法文件名验证。参考配置：

[source,json]
----
{
    "validator": "filename",
    "message": "对不起，目录名包含特殊字符，请检查！"
}
----

==== required

必填验证，此验证器和最早示例中的默认 `required` 有所区别，此验证器属于增强型，可检查 `Array`，`Object` 等复杂数据结构。

[source,json]
----
{
    "validator": "required",
    "message": "对不起，订单项不可为空，请添加订单项！"
}
----

==== mix

最小值验证器（增强型）。参考配置：

[source,json]
----
{
    "validator": "min",
    "config": {
        "min": 0
    },
    "message": "早餐券不能为负数！"
}
----

==== max

最大值验证器（增强型）。

==== range

范围验证器。参考配置：

[source,json]
----
{
    "validator": "range",
    "config": {
        "min": 0,
        "max": 8
    },
    "message": "超预订数量只能在合理的 0 ~ 8 的范围！"
}
----

==== currency

货币验证器。参考配置：

[source,json]
----
{
    "validator": "currency",
    "message": "对不起，价格不能为负"
}
----

==== after

在目标时间之后

[source,json]
----
{
    "validator": "after",
    "message": "离店时间必须晚于到店时间！",
    "config": {
        "to": "arriveTime"
    }
}
----

==== before

在目标时间之前

==== less

增强型小于某值

[source,json]
----
{
    "validator": "less",
    "message": "拆分金额必须小于原始金额！",
    "config": {
        "to": "amount"
    }
}
----

==== lessOr

增强型小于等于某值

==== great

增强型大于某值

==== greatOr

增强型大于等于某值

==== same / equal

相同值验证

[source,json]
----
{
    "validator": "same",
    "message": "两次输入密码不一致！",
    "config": {
        "to": "npassword"
    },
    "condition": [
        "to.length >= 8"
    ]
}
----

==== diff

不同值验证
