ifndef::imagesdir[:imagesdir: ../images]
:data-uri:
:table-caption!:

=== Ui库

界面的快速开发依赖新库 `ui` 中提供的智能化开发模块。

==== `Ui.smartList`

`smartList` 的骨架代码如下：

[source,js]
----
import Ui from "ui";
import Ex from 'ex';
import Ux from 'ux';

export default Ui.smartList({
    ns: require("./Cab.json"),
    name: "Integration.SMS",
    logger: "toolkit",
    Options: {
        rm: [
            "form.filter",      // 关闭高级搜索表单
            "op.extra.export",  // 按钮：导出
            "op.extra.import",  // 按钮：导入
            "op.batch.delete",  // 按钮：批量删除
            "op.batch.edit",    // 按钮：批量编辑
        ]
    },
    Form: {
        name: "FormSms",
        yoOp: {
            A: "/api/i-integration",
            S: "/api/i-integration/:key",
            D: "/api/i-integration/:key"
        }
    },
    componentInit: (reference) => {
        Ex.yiAssist(reference, {})
            .then(Ux.ready).then(Ux.pipe(reference))
    }
})
----

快速开发模式主要调用 `Ui.smartList` 的API完成页面的综合性定制，此处针对 `Ui.smartList` 做个简易的说明，这个函数只有一个参数：

[source,js]
----
const smartList = (configuration = {}) => {
    // ...
}
----

`configuration` 的配置项数据结构如下：

[options="header",cols="2,8",title="基础配置"]
|====
|配置项|含义
|`ns` |关联名空间连接文件，此处必须调用 `require` 方法连接名空间。
|`name` |这个是页面名称，您可以随意设置页面名称，在开发过程中此名称会出现在浏览器的开发工具 `console` 中，您可以精确定位日志是从什么地方出来的。
|`logger` |可使用的日志器，日志器必须是合法日志器，参考 **日志器** 章节。
|`Cab` |（驼峰命名），若不指定此选项，那么当前页面会直接绑定到 **名空间** 下 `UI.json` 文件中，若您要指定就必须指定 Cab 对象中 `page` 属性（不带 `.json` 后缀）。
|`Options` |（驼峰命名），您可以设置 `rm` 属性关闭列表页中不使用的选项，选项参考下一章节单独说明。
|`Form` a|（驼峰命名），此处的 `Form` 属性对应 `Ui.smartForm` 中的配置信息，常用四个属性如：

- `name`：表单的名称
- `yoOp`：当前操作中的常用 RESTful 地址
+
--
- A：添加接口（POST方法）
- S：保存接口（PUT方法）
- D：删除接口（DELETE方法）
--
|====

[options="header",cols="2,8",title="生命周期函数"]
|====
|配置项|含义
|`componentInit`|对应 React 中的 `componentDidMount` 生命周期。
|`componentUp`|对应 React 中的 `componentDidUpdate` 生命周期。
|`componentYo`|对应 React 中的 `render` 生命周期。
|====

[options="header",cols="2,8",title="Extension扩展"]
|====
|配置项|含义
|`yoOp`|扩展属性 `$op`，对操作按钮执行变更实现按钮扩展。
|`yoExecutor`|扩展属性 `$executor`，主要针对横行中的操作，如 **编辑、删除、权限设置** 等，列表行操作必须。
|`yoPlugins`|扩展属性 `$plugins`，针对 Zero Extension 组件渲染支持的插件进行定义。
|`yoRenders`|扩展属性 `$renders`，自定义 **表单渲染器**，对应 `<ExForm/>` 中的 `$renders` 实现表单交互式组件的自定义。
|`yoRx`|扩展属性 `rx` 前缀类型的函数继承。
|`renderAddOn`|列表之下的 **附加渲染器**，可渲染额外区域的相关组件。
|====


==== `Ui.smartForm`

`smartForm` 实际是快速绑定表单专用资源文件实现表单级的快速开发模式，这种场景下不需要您提供额外的表单代码文件，外层若调用 `smartList`，那么此处的 `Form` 配置中的每一种表单配置都会触发一次 `smartForm` 实现标准模式下三种表单的快速配置流程。

此函数签名如：

[source,js]
----
const smartForm = (configurationForm = {}, mode) => {
    // ....
}
----

[options="header",cols="2,8",title="基础配置"]
|====
|`ns` |关联名空间连接文件，此处必须调用 `require` 方法连接名空间。
|`name` |这个是表单名称，您可以随意设置表单名称，在开发过程中此名称会出现在浏览器的开发工具 `console` 中。
|`Cab` |（驼峰命名），默认会使用标准化代码针对 `FormAdd, FormEdit, FormFilter` 三种表单绑定不同的资源文件，默认绑定 `UI.Add.json、UI.Edit.json，UI.Filter.json`。
|====

[options="header",cols="2,8",title="生命周期函数"]
|====
|配置项|含义
|`componentInit`|对应 React 中的 `componentDidMount` 生命周期。
|`componentUp`|对应 React 中的 `componentDidUpdate` 生命周期。
|`componentYo`|对应 React 中的 `render` 生命周期。
|`componentValue`|表单特殊的生命周期执行，在 `render` 中再次执行初始化值的相关计算流程。
|====

[options="header",cols="2,8",title="Extension扩展"]
|====
|配置项|含义
|`yoOp` |扩展属性 `$op`，表单提交专用函数（直接和 `aiAction` 绑定的按钮函数，一般是二阶函数）。
|`yoJsx` |扩展属性 `$renders`，表单自定义渲染器，若表单中的组件依赖 **用户自定义组件**，可直接使用此属性扩展。
|`yoAcl` |扩展属性 `$edition`，针对表单执行 ACL 的权限控制 **自定义**。
|`yoPlugins` |扩展属性 `$plugins`，针对表单部分插件配置，可挂载外置插件。
|====

[CAUTION]
====
上述提供的所有 `yo` 类型的扩展属性都包含两种形态：

- `Funcation` 形态，直接执行过后产生所需的配置项 `{}`。
- `Object` 形态，直接将此配置项作为 **扩展点** 返回。
====

==== 快速配置

若您使用了 `Ui.smartXxx` 的方式做 **列表** 和 **表单** 的快速开发，那么配置文件也会大大简化（达到了快速开发的目的）。参考配置如：

[source,json]
----
{
    "_assist": {
        "zero.integration": {
            "uri": "/api/type/tabulars/:type",
            "magic": {
                "type": "FIX:zero.integration"
            }
        }
    },
    "_grid": {
        "module": {
            "NAME": "邮件配置",
            "MODULE": "i-integration",
            "IDENTIFIER": "i.integration"
        },
        "query": {
            "criteria": {
                "sigma": "PROP:app.sigma",
                "type": "email",
                "": "OPERATOR:AND"
            }
        },
        "options": {
            "tabs.title": "Email服务器配置",
            "tabs.container": true,
            "search.advanced": false
        }
    }
}
----

上述配置文件需说明：

- `_assist` 部分依旧，用于提取辅助数据，不仅如此，若要加载辅助数据您还需在 `componentInit` 中手工书写代码（类似 `componentDidMount` 函数）。
- `module` 参数，此参数用于模块鉴别，参数含义如下：

+
--
[options="header", cols="2,8"]
|====
|参数名|含义
|`NAME` |呈现当前模块的显示主体模型文字。
|`MODULE` |对应 `crud` 模型中的 `name`，构造标准化模块时 `:actor` 部分专用。
|`IDENTIFIER` |当前管理模块的模型标识符。
|====
--

- `query.criteria` 参数，直接书写当前页面的 `Qr` 查询参数。
- `options` 参数，若您不想使用默认值，则可以直接在此处更改 `options` 配置参数对列表进行修订。