ifndef::imagesdir[:imagesdir: ./images]
:data-uri:

== 命令说明

=== 基础执行

直接从 `Gogo Command` 后台执行，示例如：

[source,bash]
----
g! service bundle all
[ ZERO ] Command : all
No service registered in current bundle. name = io.zerows.zero-core-ams-specification
----------------------------------------
No service registered in current bundle. name = io.zerows.zero-core-entry-osgi
----------------------------------------
Bundle: ( id = 16, name = io.zerows.zero-core-runtime-configuration )
Service Registered List:
   [io.zerows.core.configuration.osgi.service.EnergyOption]
      com.aisz.platform-entry-osgi
   [io.zerows.core.configuration.osgi.RuntimeConfigurationCommand]
----------------------------------------
Bundle: ( id = 17, name = io.zerows.zero-core-runtime-metadata )
Service Registered List:
   [io.zerows.core.metadata.osgi.service.EnergyFailure]
      io.zerows.zero-core-runtime-metadata
      io.zerows.zero-core-runtime-configuration
      com.aisz.platform-entry-osgi
   [io.zerows.core.metadata.osgi.RuntimeMetadataCommand]
      org.apache.felix.gogo.runtime
----------------------------------------
----

=== 命令清单

[options="header",cols="2,2,6"]
|====
|命令|参数|说明
|`exit`|（无）| 追加的退出命令，可退出整个应用。
|`cache`| （无）|查看当前环境中的所有**组件缓存**。
|`failure error`| `all` | 查看当前环境中所有自定义异常。
|| `size` | 查看当前环境中异常数量。
|| `{BUNDLE_ID}` | 查看某个 `Bundle` 中的异常定义。
|`failure info`| `all` | 查看当前环境中所有自定义异常（前端可阅读版本）。
|`node network`| `all` | 查看 Cluster 集群详细信息。
|`node vertx`| `all` | 查看 Vertx 运行实例的详细信息。
|`service bundle`| `all` | 查看当前环境中所有注册的 OSGI 服务信息，以及服务调用者信息。
|| `{BUNDLE_ID}` | 查看某个 `Bundle` 相关的服务注册信息，以及服务调用者信息。
|====