ifndef::imagesdir[:imagesdir: ./images]
:data-uri:

== 运行环境

兼容运行旧版程序过程中，为了保证生产环境和开发环境拥有同样的目录结构，方便多个 App 实例的运行，所以针对此环境进行重新规划，以达到**单镜像、单程序**的**多目录（每个目录一个实例）**的运行模式，此模式之下配合第二管理端完整程序，您可以完成多应用的部署模式。

=== 目录结构

==== 作用

第二管理端和应用程序端的部署结构维持一致，新的目录结构作用：

- 开发环境和生产环境目录维持一致，生产环境运行时可实现绿色启动/一键部署。
- 容器化部署时可直接将 Docker 的存储挂载外置目录，并将目录中相关信息全部拷贝到目标目录中。
- 每个应用都可以开启多个 App 实例，可**多实例**运行。


==== 运行目录

[options="header",cols="4,6"]
|====
|路径|说明
|`/running/` |运行主目录
|`/running/bin/` |程序主目录
|`/running/bin/app.jar` | 入口程序
|`/running/bin/start.sh` | （脚本）启动脚本
|`/running/bin/stop.sh` | （脚本）停止脚本
|`/running/bin/lib/` | 依赖库存放目录
|`/running/instance/` | 实例配置目录
|`/running/instance/{name}` | 单个实例配置目录，开发过程中实例运行主目录、工作目录
|`/running/instance/{name}/.env.development` | 开发专用实例环境变量
|`/running/instance/{name}/.env.lock` | 实例配置锁，运行过程中检查锁文件，若锁文件存在则跳过 `run-configure.sh` 配置脚本
|`/running/instance/{name}/keys` | 安全运行证书配置
|`/running/instance/{name}/conf` | 实例运行配置程序，开发中 `src/main/resources` 目录中的内容。
|`/running/instance/{name}/database` | 实例运行数据库目录
|`/running/instance/{name}/logs` | 实例运行日志目录
|`/running/util/inst/` | 指令程序运行目录
|`/running/util/inst/inst-load.jar` | （指令）数据导入程序
|`/running/util/inst/inst-menu.jar` | （指令）菜单规划程序
|`/running/util/inst/inst-atom.jar` | （指令）动态建模程序
|====

=== 初始化

==== 应用端

1. 在 `demo` 目录中配置相关环境变量，参考如：

+
--
[source,bash]
----
#!/usr/bin/env bash
# -------- playbook.database.yml
export DB_TYPE=MYSQL                      # 数据库类型
# 数据库名关键字，最终生成
# DB_HOTEL_001
# DB_HOTEL_001_WF
export DB_INSTANCE=HOTEL_001

# database 应用账号密码
export DB_APP_USER=??
export DB_APP_PASS=??
# database 脚本执行所需（zero账号密码）
export DB_PASSWORD=??

# -------- playbook.conf.vertx.yml
export PORT_WEB=7105                      # 前端接口
export PORT_API=7185                      # 后端接口

# -------- 应用专用环境变量
# export DB_ENV=DEV
export Z_APP=app.micro.hotel              # 应用名
export Z_HED_ENABLED=true                 # 是否开启 HED
export Z_SIS_STORE=/Users/lang/zero-store # 集成服务上传下载存储配置
# environment.json 所需
export APP_SIGMA=??
export APP_ID=??
export APP_TENANT=??
export APP_HOTEL=??

# export Z_HED=io.zerows.plugins.store.liquibase.hed.HEDCore
----
--

2. 执行初始化编译

+
--
[source,bash]
----
mvn -Pinit clean package install
----
--

3. 分布执行实例初始化脚本

+
--
[source,bash]
----
# 语法
# init.sh {instance} {dbtype}
# 第一步
./init.sh hotel-001 MYSQL
# 第二步
./configure.sh hotel-002 MYSQL
# 注意此处实例名和 demo 中的文件名对应
----
--