ifndef::imagesdir[:imagesdir: ../images]
:data-uri:

=== 元数据规范

新版Zero从原来的 `zero-co` 项目中分裂出一个新项目 `zero-ams`，全称为 `Agreed Metadata Specification`（翻译为：达成共识的元模型规范），该项目具备非常强的扩展性，可适用于任何和 Vert.x 相关的项目，提供了一个项目的基础底座，此项目为大量 Vert.x 项目提供了一种基础**标准**，即使您不使用Zero也可以在 Vert.x 项目中使用此依赖来完善**元数据规范**。

==== 设计原则

> 抽象、体系、复用、深度。

`zero-ams` 的设计主要是重新抽象了 Zero 核心框架底层的功能包，用于跨框架执行，理论上只能在 Vert.x 框架中使用，但在实战中若和Spring做集成，可直接引入 `zero-ams` 的依赖包直接在 Spring 中使用。**AMS** 的设计核心在于：

- 弥补JVM中部分语法定义处理得不当的地方，让整个环境变得更加自由（JVM支持函数式编程是8+之后的事，由于本身设计的缺陷是完全支持函数式编程理论的）。
- 扩展部分JVM中的API以适应更多偏向于**业务计算**的场景，解决大部分重复劳动的工作量，如：MD5加密、序列化、IO等。
- 从实战经验中总结相关教训，提供和平台无关的基础组件，让您的项目和框架本身语义（羽翼）变得更加丰满。
- 定义一套基于：**运行时、建模、云端** 的 **纯接口规范**（这是私货），让您在处理平台级应用时有一个设计层面的思考。

虽然从实际过程中可以看到这部分内容的设计略有冗余，但若您选择使用 Vert.x 作底层框架时，我相信这套基础规范可以让项目实施和交付变得更加流畅。

==== 功能支持表

**AMS** 支持的功能点参考下表：

[options="header",cols="20,80"]
|====
|功能|说明
|逆向注解 a|提供新注解，针对特殊的功能实现元数据分析（代码分析代码的模式）：

- `@Development`：开发注解，定义部分私有成员辅助开发，可使用代码和脚本对项目本身执行分析。
- `@HighOrder`：连接注解，定义和 ams 项目相关的工具调用，以标记代码。
- `@Memory`：缓存注解，可对Cc架构执行缓存注解。
- `@ChatGPT`：使用ChatGPT编写的机器代码部分

逆向注解是非必须，若没有在代码中标注，仅在**逆向工程**中无法收集相关元数据，对正常程序的运行不产生任何影响。
|通用数据结构|提供部分通用数据结构定义，不带任何业务色彩，纯功能支持型内容。
|异常架构 a|提供任何项目都可使用的异常规划，可加载不同资源文件实现扩展异常定义，动参和继承相结合，实现项级的完整异常体系，完整抽象层异常体系如下：

[source,bash]
----
java.lang.Throwable

  -- java.lang.Exception
  
        # 编译时顶级 Checked 异常
     -- io.horizon.exception.ProgramException   
     
           # 和资源文档绑定的检查异常，通常在编程过程中可抛出
           # 1. 配置强化校验
           # 2. 容器后台程序校验
        -- io.horizon.exception.DaemonException 
        
     -- java.lang.RuntimeException
     
           # 运行时顶级抽象异常
        -- io.horizon.exception.AbstractException  
        
              # 内部专用异常，不绑定资源文件，直接编程使用硬编码方式定义
           -- io.horizon.exception.InternalException   
           
              # 和资源文档绑定的启动异常，在容器启动过程中出现
              # 1. 模型校验
              # 2. 容器启动校验
           -- io.horizon.exception.BootingException     
           
              # Web容器运行过程中的通用异常
              # 通用异常包括常见的：500、501、400、401、403 等常见异常
           -- io.horizon.exception.WebException         
----
|函数包 a|提供 *类* 级别的函数顶层包 **HFn**（Java语法糖），实现工具独立规划和分析，且在函数包中引入增强的防御式、文学式编程范式，以更优雅的方式处理JVM级别的异常，且扩展 *函数接口* 让Java可支持 lambda 中的检查异常抛出机制。

- 由于Java语言中的 `@FunctionalInterface` 内部不支持异常捕捉，若您在 lambda 块中写了 **检查异常** 抛出相关的代码会导致 **编译错误**，**HFn** 扩展 Throwable 函数接口定义了可抛异常的接口。
- 除开官方提供的 `Predicate、Supplier、Consumer、Funcation` 四种常用函数式接口之外，**HFn** 定以了纯执行类接口 `Actuator`，此接口 **无参数，且返回值为void**。
- `try-catch` 的小封装，提供几个级别的快速函数执行接口，不同前缀处理不同类型的异常：
+
--
- `bug`：处理所有 `ProgramException` 类型的异常，这种类型的API要求底层必须以 throws 抛出对应异常，属于静态检查。
- `fail`：处理所有 `Exception` 类型的异常，虽然 `Exception` 是检查性异常，API封装后外层 lambda 不抛出。
- `jvm`：处理所有 `Throwable` 类型的异常，API封装后外层 lambda 不抛出。
- `run`：广泛定义 `RuntimeException` 级别的异常，API内部可随意抛出这种类型异常，不检查。
--
- 在原始异常结构中定义了新的异常体系，和 **AMS** 中的部分 SPI 插件接口对接，实现任意框架级的资源文件扩展，除开 Zero 中的 `vertx-error.yml` 中的实现，您可以开发自定义的资源文件实现方案。
- 提供常用的 **异步** 编排组合函数，您可以将多个异步 **Monad** 组合成复杂结构：**串行、并行、网状、树状** 等——编排是异步编程中的重点，也是 Zero 框架本身的一大亮点。
- 开放部分类的 **高阶** 组合函数，您可以在二阶以上实现基础的编排工作，近似于标准库中的 `BiXx`，但扩展部分还可能包含 `TiXx` 的更加高阶的函数模型。

|规范 a|提供 *运行时、建模、云端* 三种规范接口定义，这种类型的定义仅限 `interface` 关键字，所以整个 **AMS** 中不提供任何实现，代码内部注释比较齐全，所有接口都是 `H` 前缀的高阶设计，主要包含四大类：

- 基础功能类
- 建模类
- 云端类
- 开发定制类
|工具包 a|提供 *类* 级别的工具顶层包 `HUt`，实现工具独立调用，工具支持：

- 彩色Console日志
- 对象比对、值比对
- 加密/解密模块（MD5、RSA、公私钥非对称、Base64等）
- 集合运算（添加、基础、聚集、查找、拉平、反序、分组、映射、移除等）
- 环境变量加载
- 异常快速构造
- String / JsonObject / JsonArray和其他数据结构的相互转换
- IO目录、文件读取、不同格式文件读取（包括jar内部资源文件）、以及大文件（>10G）算法
- 判断性原子函数
- 专用 lambda 模式的集合迭代
- *建模* 抽象工具类
- 网络检查专用功能包
- 日期/时间 格式化、转换、解析包
- 随机数、字符串、验证码生成功能包
- 安全值读写
- 常用反射包（单件、实例、池化、SPI级核心反射）
- 表达式解析包
- AOP插件执行包
- Jackson 基础序列化/反序列化包
|UCA架构 a|全称为 User Component Architecture，用户自定义组件架构，规范中支持的自定义组件如：

- CC缓存架构：Cloud Cache，支持内存缓存、异步缓存、线程缓存，全局统一管理缓存
- 比对组件：可针对Java语言中的强类型执行通用比对，差异性比对、等价性比对
- 转换组件：特殊数据结构之间的相互转换功能函数
- 加解密组件：公私钥非对称加解密专用组件，内部支持HED实现敏感数据加解密功能
- 日志组件：基础日志、扩展日志专用组件，提供可扩展日志结构，外可连ELK平台
- 本地文件组件：提供本地文件类似 `mkdir / rm` 等常用命令的文件操作
- 网络组件：IPv4和IPv6专用网络检查功能包
- Qr查询引擎组件：支持 Qr 查询引擎语法的专用组件
- 启动组件：可插拔启动器架构的核心组件
- AOP组件：新版AOP编排组件
|====

==== 框架对接

`zero-ams` 中的异常架构是基于 **SPI** 扩展，若要对接新框架如Spring，则需要实现基础资源关联部分的SPI，才可以和 `zero-ams` 完整集成，否则 *可配置* 异常架构无法在新框架中发挥作用，本章主要讲解对接步骤以及注意事项，您可以完全隔离 Zero 框架在任何支持 Vert.x 的结构中直接使用此教程。

[CAUTION]
====
SPI（Service Provider Interface）是Java语言中原生的一种机制，用于实现模块化、可扩展性的应用程序，它允许开发者定义一组接口（或抽象类），而允许不同的实现者提供具体的视线，这些实现可以在运行时被动态加载或替换，而无需修改源代码。它使用场景如下：

- 插件系统
- 驱动程序加载
- 扩展框架

它是一种实现松耦合、可扩展、可插拔的方式，允许开发人员在不改变核心功能的前提下扩展应用程序。
====

===== 资源文件

新框架对接中基本要求：必须提供异常资源文件连接，如 Zero 中使用 `vertx-error.yml` 资源文件做绑定，您可以在新的框架如 Spring 中参考 `spring-up` 项目中的配置，使用可国际化的 `application-error.yml` 资源文件做绑定内容。SPI实现过程中并没有强制要求您从文件路径中加载资源，只是要求从返回的数据结构中（JsonObject类型）实现两个核心的数据结构

- 异常代码/系统信息表
- 异常代码/业务信息表（可选，根据业务需求定义）

这两个信息表在Zero框架中位于 `vertx-error.yml / vertx-readable.yml` 两个资源文件定义，您可以在自己对接其他框架时，采用其他实现手段来完成，不影响整体结构。以下是 Zero 框架中的异常信息表的范例：

_vertx-error.yml_

[source,yaml]
----
# 20001 - 29999
# Thirt part error for different integration
E20001: (401) - Qiy interface of "/iqiyi/authorize" met errors, code = {0}, message = {1}
E20002: (401) - Qiy token record does not contain "access_token", client_id = {0}

E80203: "(449) - (RBAC) The user `{0}` could not be found in database"
E80204: "(401) - (RBAC) The user''s ( username = {0} ) password that you provided is wrong"
----

_vertx-readable.yml_

[source,yaml]
----
# 登录异常
80204: "对不起，用户名和密码错误！"
80203: "对不起，找不到您提供的用户信息！"
----

[TIP]
====
上述结构取决于 `io.horizon.spi.HorizonIo` 接口下的实现逻辑，Zero中的实现逻辑因为历史原因，两个文件的基础 *键* 命名并没有维持一致，一个是 `EXXXXX` 一个是 `XXXXX`，但若 `XXXXX` 部分相同，则代表描述的是同一个错误代码对应的信息。此处设计成**五位**是考虑到在日志打印过程中让前缀的长度维持一致，一般框架内部或扩展使用**五位**，而您若开发其他应用则考虑**六位**。
====

===== HorizonIo

对接框架，您只需要提供SPI接口 `io.horizon.spi.HorizonIo` 接口的相关实现，该接口的定义如下：

[source,java]
----
package io.horizon.spi;

import io.vertx.core.json.JsonObject;

/**
 * 资源文件加载专用SPI模式
 * - 日志器：HLogger 是高阶实现，Annal 为Zero默认实现
 * - 资源加载器：
 * --- spring 中加载 application-error.yml
 * --- vertx zero 中加载 vertx-error.yml
 * - 最终实现完整加载流程
 * 该组件SPI为底层资源加载组件，用于如下作用
 * 1. 对接不同的 Annal 扩展组件，实现日志器的替换扩展流程。
 * 2. 对接错误信息的资源提取流程，提取错误信息专用，构造成一个JsonObject包含所有资源类错误信息定义。
 *
 * @author lang : 2023/4/28
 */
public interface HorizonIo {
    /**
     * 资源加载，加载对应的异常资源文件，内部实现可自定义
     *
     * @return {@link JsonObject}
     */
    JsonObject ofError();

    /**
     * 资源加载，加载对应的异常资源文件，和 ofError() 可成对出现
     * 该方法返回的内容可直接提取可读部分，用于前端展示
     *
     * @return {@link JsonObject}
     */
    JsonObject ofFailure();

    /**
     * 日志获取器，可读取扩展日志类型，实例时基于 Class<?>
     *
     * @return {@link io.horizon.specification.uca.HLogger}
     */
    default Class<?> ofLogger() {
        return null;
    }
}
----

上述接口实现过程中，解释一下：

1. _ofError_ 用于返回 *异常代码/系统信息表*
+
--
格式如：`EXXXXX = xxxxx`
--
2. _ofFailure_ 用于返回 *异常代码/业务信息表*
+
--
格式如：`XXXXX = xxxxx`
--
3. _ofLogger_ 用于返回 `io.horizon.specification.uca.HLogger` 实现类名，反射替换原始日志记录器（若不替换则使用默认的 `slf4j` 接口。

上述实现完成之后，您可以在 `/META-INF/services/io.horizon.spi.HorizonIo` 中追加默认SPI的实现类，在自己的项目中直接对接异常架构，如此您的系统就可以享受 `zero-ams` 带来的完整的可配置异常架构和函数模型，若您使用的是 Zero 框架，则不需要做任何对接，默认的 `zero-co` 中已经包含了和 Zero 相关的所有实现。

====
最后需说明一点，上述接口的实现在 JVM 中会出现三种不同场景，都和类加载器有关：

- 标准场景：直接使用单个JVM运行 jar 程序，这种模式下无需额外配置。
- OSGI场景：由于OSGI场景下类加载器是相互隔离或独立的，所以在实现 `HorizonIo` 的过程中，您需要先精确定位类加载器，再读取相关配置才可以。
- Spring场景：Spring 框架对类加载器本身做过调整，特别是IO读取文件这一层，若要对接 Spring 您必须保证底层 IO 访问的资源是可达的。
====