ifndef::imagesdir[:imagesdir: ../images]
:data-uri:
:table-caption!:
:sectlinks:
:linkattrs:

==== 授权完整流程

前文中讲解了 *资源请求流程* 的完整步骤，由于认证流程相对简单（会话校验、令牌校验），而授权流程主要会包含三个核心步骤：

1. 基本授权：用户是否有权访问该资源。
2. 安全视图：当前资源是否启用了安全视图。
3. 访问者：启用了安全视图的场景中是否执行访问者流程。

本章节主要针对基本授权流程细节进行讲解（其中 *基本授权* 属于资源请求流程的后半部分内容）。

===== 标准化输入

认证流程通过后，授权最初会拿到如下输入数据信息（该数据同时也是调用 `user.principal()` 的结果）：

[source,json]
----
{
    "user": "xxx",
    "session": "xxx",
    "habitus": "xxx",
    "access_token": "xxx",
}
----

该数据信息会在Zero安全框架内部执行标准化，标准化结果为：

[source,json]
----
{
    "user": "xxx",
    "session": "xxx",
    "habitus": "xxx",
    "access_token": "xxx",
    "metadata": {
        "method": "xxx",
        "uri": "xxx",
        "requestUri": "xxx",
        "view": {
            "view": "xxx",
            "position"; "xxx"
        }
    },
    "headers": {
    
    }
}
----

简单说明几点：

1. 标准化过程追加了本次请求信息，使用该请求信息可直接提取 `S_ACTION`，而 `S_ACTION` 和 `S_RESOURCE` 是一对一绑定，等价于可直接提取资源信息。
2. 视图存储采用了 `Vis` 对象（专用视图对象），包含了 `view` 和 `position` 两个维度。
3. `headers` 中主要捕捉自定义请求头，类似 `X-Sigma`, `X-Lang` 等这种。

[CAUTION]
====
还需要说明的一点就是注意 `uri` 和 `requestUri` 的区别，一般在后端定义资源时会采用 `uri`，举个例子（按工号读取某个员工）：

- 后端定义GET接口：`/api/employee/:workNumber`，此处的路径就是 `uri`，后端查询 `S_ACTION` 以它为主。
- 真正发送请求时：`/api/employee/20230201`，此处的路径就是 `requestUri`。

两种不同的URI在不同的场景会分别参与不同后续流程运算。

====

===== 基本授权步骤

1. 使用标准化输入处理之后的数据构造 `ScResource` 对象（和 `ScUser` 类似是对资源结构的封装）。
2. 从 `ScResource` 中计算提取资源池中的资源键（`resource-<method>:<uri>`），使用该资源键访问 link:#__SEC_CACHE_RESOURCE[资源池,window="_blank"]。
+
--
- 如果资源池存在直接走安全视图流程。
- 资源池中不存在则走步骤三。
--
3. 根据请求数据（ `uri` 和 `method` ）从安全操作中提取 `S_ACTION` 记录锁定本次请求的安全操作。
4. 根据安全操作提取绑定的资源记录，若资源所需操作等级大于了安全操作等级，证明资源出现了状况（比如升级、迁移等），安全操作失效。
5. 操作检查结束后，根据提取的所有信息回写资源池，并完成和资源池的同步。

===== 视图流程

资源同步完成后，就开始根据资源读取当前登录用户的视图信息，视图信息读取分两步：

1. 用户视图（高优先级），如果存在用户视图则直接忽略角色视图。
2. 角色视图，用户未做任何视图管理时资源的默认视图。

视图读取在消费端章节已经多次提及，此处就不赘述，用户视图实际是挂在用户登录的 `habitus` 缓存之下，视图键的计算如：

[source,bash]
----
session-<method>:<uri>:<position>/<view>
----

[CAUTION]
====
视图在初始化时实际是针对资源池的 *双读双写* 计算，一方面确保资源池中的资源数据已经是经过了同步的数据，另外一方面保证当前视图绑定的资源信息具有强一致性。

- 如果直接从用户的 `habitus` 缓存之下可以读取视图信息，则跳过初始化视图的流程。
- 无法从缓存中提取视图信息时，则执行初始化流程（先用户、再角色）的提取模式。

====

资源访问者流程在数据域后期执行，下一章节将会详细介绍。前期执行该流程会导致访问者语法只能根据输入处理，无法根据存储数据处理导致访问者功能缺失，无法处理二阶段读写专用场景。

