ifndef::imagesdir[:imagesdir: ../images]
:data-uri:

=== 数据规范[[__06_SPEC_IS_DATA]]

==== 设计理念

系统后端最早的前后端通常会以自由格式返回（Zero中的 `freedom` 配置），比如服务端响应数据是 `String、Boolean、Integer、Json`，这种格式的诟病有以下几点：

- 自由格式在前端解析没法统一，虽然JS是弱类型语言，但依旧需要写一部分适配脚本来针对不同的数据格式执行判断、解析、计算流程。
- 扩展性不够，如果前后端存在 `AOP` 层或扩展性脚本，即前端和后端需要执行一部分 *元数据沟通*，这种格式由于没有携带任何信息，最终会导致再次请求来实现元数据的提取。
- 格式太自由无法形成统一的数据规范，自动化脚本处理起来也会出现特殊性编程。

==== 请求头

Zero中有自定义请求头信息，所以后端对 MIME 级以及请求头这一级的内容做了限定，所有请求必须遵循如下表格请求头基本要求：

[options="header",cols="15,15,70"]
|====
|请求头|必须/可选|含义（值）
|Content-Type | Required | 除上传接口以外，通常使用 `application/json`。
|X-Sigma | Conditional | 应用统一标识符
|X-App-Id | Conditional | 应用主键，对应 `X_APP` 表。
|X-App-Key | Conditional | 应用敏感信息头，对应 `X_APP` 表。
|X-Lang | Conditional | 应用使用的语言环境变量，默认 `cn` 。
|X-Tenant-Id | Conditional | 多租户平台使用的租户主键。
|====

==== 标准格式

Zero Extension中定义的标准响应格式如下：

[source,json]
----
{
    "data": "xxx",
    "__extension": {},
    "__metadata": {},
    "__acl": {},
    "__qr": {}
}
----

上述格式是目前系统已经在使用的核心格式，从格式中可以知道，真正的数据部分只是 `data` 节点，而此时 `data` 节点的数据格式可以按照自己的需求进行定义，比如 `String, Boolean, Integer, JsonObject, JsonArray` 等等，而JS在解析时就不用关注拉取到响应时的解析，直接提取 `data` 节点即可。整个格式的含义表如下：

[options="header",cols="15,85"]
|====
|节点|含义
|`data` |异构数据格式，常见数据格式包含三大类：Json对象、Json数组、基础类型。
|`__extension` |扩展格式，追加扩展插件执行数据响应在交互级的插件扩展以确认数据本身的合法性。
|`__metadata` |动态接口中，用于存储附加数据的元数据信息，定义了当前数据信息中的 *业务定义*，系统定义可以使用响应头。
|`__acl` |ACL授权流程中，可使用该字段描述本次数据的ACL权限信息。
|`__qr` |（特殊历史场景），在列表响应中，使用该属性记录列表响应的视图信息以防止每次进入界面做个人视图的二次读取和加载。
|====

[CAUTION]
====
异构数据格式的优势在于前后端解析可以一致且可以追加或携带部分 *元数据* 信息，在企业级应用过程中尤其实用，当然若您不想实用 Zero Extension则可直接在配置中开启 `freedom` 模式，那么上述数据规范就会失效，远程生成什么响应前端就会得到什么响应。
====

==== 异常格式

异常发生时，HTTP状态代码在 *Zero规范* 中不允许使用 `2XX` 的代码，不同的状态代码在容器内部会走不同流程，遵循 RESTful 规范定义状态代码是框架推荐的。

- `4XX`：客户端异常
- `5XX`：服务端异常

Zero中的统一异常格式信息如下：

[source,json]
----
{
    "code": xxx,
    "message": "（系统异常信息）",
    "info": "（用户可读异常）"
}
----

参考下边表格理解其含义：

[options="header",cols="15,85"]
|====
|参数|说明
|code|格式通常为负数5位或6位（自定义），5位是Zero原生异常代码表中的内容，6位通常是扩展定义，可根据错误代码直接查询当前请求出错原因。
|message|系统异常信息，通常是后端生成的标准化格式异常，可以帮助开发人员做接口调试（`vertx-error.yml` 中可配置）。
|info|（可选）业务异常信息，如果异常需要转换成业务异常信息在系统使用时返回给调用端，则需要启用（`vertx-readible.yml` 中可配置）。
|====

[TIP]
====
`vertx-readible.yml` 文件中的内容示例如下：

[source,yaml]
----
# 登录异常
80204: "对不起，用户名和密码错误！"
80203: "对不起，找不到您提供的用户信息！"
----

其中 `80204` 就是该异常的 `code` 值，虽然返回是负数，但定义时由于取了 *绝对值*，所以可以直接使用代码做键值。上述代码对应 `vertx-error.yml` 文件中的内容如下（注意系统异常带 `E` 前缀）：

[source,yaml]
----
E80204: "(401) - (RBAC) The user''s ( username = {0} ) password that you provided is wrong"
E80205: "(403) - (RBAC) The profile required `{0}`, but current profile is `{1}`"
----

====